// Copyright 2020 The Alexandria Foundation
//
// Licensed under the GNU Affero General Public License, Version 3.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.gnu.org/licenses/agpl-3.0.en.html
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package shared

import "golang.org/x/text/language"

// LangMap language map to fetch with O(1) performance languages by ISO Codes
type LangMap map[string]language.Tag

// SupportedLangMap supported language map
var SupportedLangMap = LangMap{
	language.AmericanEnglish.String():      language.AmericanEnglish,
	language.Albanian.String():             language.Albanian,
	language.Arabic.String():               language.Arabic,
	language.Armenian.String():             language.Armenian,
	language.Azerbaijani.String():          language.Azerbaijani,
	language.BritishEnglish.String():       language.BritishEnglish,
	language.BrazilianPortuguese.String():  language.BrazilianPortuguese,
	language.Bulgarian.String():            language.Bulgarian,
	language.Catalan.String():              language.Catalan,
	language.CanadianFrench.String():       language.CanadianFrench,
	language.Chinese.String():              language.Chinese,
	language.Croatian.String():             language.Croatian,
	language.Czech.String():                language.Czech,
	language.Dutch.String():                language.Dutch,
	language.Danish.String():               language.Danish,
	language.EuropeanSpanish.String():      language.EuropeanSpanish,
	language.English.String():              language.English,
	language.Estonian.String():             language.Estonian,
	language.EuropeanPortuguese.String():   language.EuropeanPortuguese,
	language.French.String():               language.French,
	language.Filipino.String():             language.Filipino,
	language.Finnish.String():              language.Finnish,
	language.Georgian.String():             language.Georgian,
	language.German.String():               language.German,
	language.Greek.String():                language.Greek,
	language.Hebrew.String():               language.Hebrew,
	language.Hindi.String():                language.Hindi,
	language.Hungarian.String():            language.Hungarian,
	language.Icelandic.String():            language.Icelandic,
	language.Indonesian.String():           language.Indonesian,
	language.Italian.String():              language.Italian,
	language.Japanese.String():             language.Japanese,
	language.Korean.String():               language.Korean,
	language.LatinAmericanSpanish.String(): language.LatinAmericanSpanish,
	language.Lao.String():                  language.Lao,
	language.Lithuanian.String():           language.Lithuanian,
	language.Macedonian.String():           language.Macedonian,
	language.Malay.String():                language.Malay,
	language.Mongolian.String():            language.Mongolian,
	language.ModernStandardArabic.String(): language.ModernStandardArabic,
	language.Nepali.String():               language.Nepali,
	language.Norwegian.String():            language.Norwegian,
	language.Persian.String():              language.Persian,
	language.Polish.String():               language.Polish,
	language.Portuguese.String():           language.Portuguese,
	language.Romanian.String():             language.Romanian,
	language.Russian.String():              language.Russian,
	language.Spanish.String():              language.Spanish,
	language.Serbian.String():              language.Serbian,
	language.SerbianLatin.String():         language.SerbianLatin,
	language.SimplifiedChinese.String():    language.SimplifiedChinese,
	language.Slovak.String():               language.Slovak,
	language.Slovenian.String():            language.Slovenian,
	language.Swedish.String():              language.Swedish,
	language.Thai.String():                 language.Thai,
	language.TraditionalChinese.String():   language.TraditionalChinese,
	language.Turkish.String():              language.Turkish,
	language.Ukrainian.String():            language.Ukrainian,
	language.Uzbek.String():                language.Uzbek,
	language.Vietnamese.String():           language.Vietnamese,
	language.Zulu.String():                 language.Zulu,
}

// SupportedLang languages supported by Alexandria
var SupportedLang = []language.Tag{
	language.AmericanEnglish,
	language.Albanian,
	language.Arabic,
	language.Armenian,
	language.Azerbaijani,
	language.BritishEnglish,
	language.BrazilianPortuguese,
	language.Bulgarian,
	language.Catalan,
	language.CanadianFrench,
	language.Chinese,
	language.Croatian,
	language.Czech,
	language.Dutch,
	language.Danish,
	language.EuropeanSpanish,
	language.English,
	language.Estonian,
	language.EuropeanPortuguese,
	language.French,
	language.Filipino,
	language.Finnish,
	language.Georgian,
	language.German,
	language.Greek,
	language.Hebrew,
	language.Hindi,
	language.Hungarian,
	language.Icelandic,
	language.Indonesian,
	language.Italian,
	language.Japanese,
	language.Korean,
	language.LatinAmericanSpanish,
	language.Lao,
	language.Lithuanian,
	language.Macedonian,
	language.Malay,
	language.Mongolian,
	language.ModernStandardArabic,
	language.Nepali,
	language.Norwegian,
	language.Persian,
	language.Polish,
	language.Portuguese,
	language.Romanian,
	language.Russian,
	language.Spanish,
	language.Serbian,
	language.SerbianLatin,
	language.SimplifiedChinese,
	language.Slovak,
	language.Slovenian,
	language.Swedish,
	language.Thai,
	language.TraditionalChinese,
	language.Turkish,
	language.Ukrainian,
	language.Uzbek,
	language.Vietnamese,
	language.Zulu,
}
